/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * twoDatesIP.java
 *
 * Created on Apr 10, 2010, 3:07:32 PM
 */

package frontend;
import javax.swing.*;
/**
 *
 * @author USER1
 */
public class twoDatesIP extends javax.swing.JFrame {
public String tday100,tmonth100,tyear100,tday200,tmonth200,tyear200;
public static String reqdate1,reqdate2,IPadd;
    /** Creates new form twoDatesIP */
    public twoDatesIP() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        day100 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        month100 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        year100 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        day200 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        month200 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        year200 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("TRAFFIC REPORT BETWEEN GIVEN TWO DATES & IP ADDRESS");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Choose From Date");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("  Day");

        day100.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day1","01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day100ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("Month");

        month100.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month1","January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month100ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel11.setForeground(new java.awt.Color(153, 0, 153));
        jLabel11.setText("Year");

        year100.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "year1","2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        year100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year100ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Choose To Date");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("  Day");

        day200.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day2","01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day200ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel10.setForeground(new java.awt.Color(153, 0, 153));
        jLabel10.setText("Month");

        month200.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month2","January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month200ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Year");

        year200.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "year2","2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        year200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year200ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel12.setForeground(new java.awt.Color(153, 0, 153));
        jLabel12.setText("Enter IP Address");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jToggleButton2.setForeground(new java.awt.Color(153, 0, 153));
        jToggleButton2.setText("OK");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jToggleButton1.setForeground(new java.awt.Color(153, 0, 153));
        jToggleButton1.setText("BACK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(day200, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(day100, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(month100, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(month200, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(year200, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(year100, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(271, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(190, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(month100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(year100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(day100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(month200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(year200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void day100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day100ActionPerformed
        // TODO add your handling code here:
          Object  team=day100.getSelectedItem();
 tday100=team.toString();
}//GEN-LAST:event_day100ActionPerformed

    private void day200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day200ActionPerformed
        // TODO add your handling code here:
         Object  team=day200.getSelectedItem();
 tday200=team.toString();
}//GEN-LAST:event_day200ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
                       // TODO add your handling code here:
          IPadd=jTextField1.getText();
         if ((day100.getSelectedItem().equals("day1"))) {
            JOptionPane.showMessageDialog(null, "Day1 is not selected");
        } else {
            if ((month100.getSelectedItem().equals("month1"))) {
                JOptionPane.showMessageDialog(null, "Month1 is not selected");
            } else {
                if ((year100.getSelectedItem().equals("year1"))) {
                    JOptionPane.showMessageDialog(null, "Year1 is not selected");
                } else {
                if ((day200.getSelectedItem().equals("day2"))) {
            JOptionPane.showMessageDialog(null, "Day2 is not selected");
        } else {
            if ((month200.getSelectedItem().equals("month2"))) {
                JOptionPane.showMessageDialog(null, "Month2 is not selected");
            } else {
                if ((year200.getSelectedItem().equals("year2"))) {
                    JOptionPane.showMessageDialog(null, "Year2 is not selected");
                } else {
                     if(IPadd.equals(""))
                   {
                        JOptionPane.showMessageDialog(null, "IP Address is not entered");
                   }
                   else
                   {

        reqdate1=tday100;
reqdate2=tday200;
if(tmonth100.equals("January"))

{reqdate1=tyear100+"01"+reqdate1;
//reqDate2=reqDate2+"/01/"+year13;
}
else if(tmonth100.equals("February"))
    reqdate1=tyear100+"02"+reqdate1;
else if(tmonth100.equals("March"))
    reqdate1=tyear100+"03"+reqdate1;
else if(tmonth100.equals("April"))
    reqdate1=tyear100+"04"+reqdate1;
else if(tmonth100.equals("May"))
    reqdate1=tyear100+"05"+reqdate1;
else if(tmonth100.equals("June"))
    reqdate1=tyear100+"06"+reqdate1;
else if(tmonth100.equals("July"))
    reqdate1=tyear100+"07"+reqdate1;
else if(tmonth100.equals("August"))
    reqdate1= tyear100+"08"+reqdate1;
else if(tmonth100.equals("September"))
    reqdate1=tyear100+"09"+reqdate1;
else if(tmonth100.equals("October"))
    reqdate1=tyear100+"10"+reqdate1;
else if(tmonth100.equals("November"))
    reqdate1=tyear100+"11"+reqdate1;
else if(tmonth100.equals("December"))
    reqdate1=tyear100+"12"+reqdate1;



if(tmonth200.equals("January"))

{//reqDate1=reqDate1+"/01/"+year12;
reqdate2=tyear200+"01"+reqdate2;
}
else if(tmonth200.equals("February"))
    reqdate2=tyear200+"02"+reqdate2;
else if(tmonth200.equals("March"))
    reqdate2=tyear200+"03"+reqdate2;
else if(tmonth200.equals("April"))
    reqdate2=tyear200+"04"+reqdate2;
else if(tmonth200.equals("May"))
    reqdate2=tyear200+"05"+reqdate2;
else if(tmonth200.equals("June"))
    reqdate2=tyear200+"06"+reqdate2;
else if(tmonth200.equals("July"))
    reqdate2=tyear200+"07"+reqdate2;
else if(tmonth200.equals("August"))
    reqdate2=tyear200+"08"+reqdate2;
else if(tmonth200.equals("September"))
    reqdate2=tyear200+"09"+reqdate2;
else if(tmonth200.equals("October"))
    reqdate2=tyear200+"10"+reqdate2;
else if(tmonth200.equals("November"))
    reqdate2=tyear200+"11"+reqdate2;
else if(tmonth200.equals("December"))
    reqdate2=tyear200+"12"+reqdate2;

setVisible(false);
new displayReport2DateIP().setVisible(true);
                   }
                }
            }
        }
                }
            }
        }
}//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new reportOnDateIP().setVisible(true);
}//GEN-LAST:event_jToggleButton1ActionPerformed

    private void month100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month100ActionPerformed
        // TODO add your handling code here:
        Object  team=month100.getSelectedItem();
 tmonth100=team.toString();
    }//GEN-LAST:event_month100ActionPerformed

    private void month200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month200ActionPerformed
        // TODO add your handling code here:
         Object  team=month200.getSelectedItem();
 tmonth200=team.toString();
    }//GEN-LAST:event_month200ActionPerformed

    private void year100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year100ActionPerformed
        // TODO add your handling code here:
         Object  team=year100.getSelectedItem();
 tyear100=team.toString();
    }//GEN-LAST:event_year100ActionPerformed

    private void year200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year200ActionPerformed
        // TODO add your handling code here:
         Object  team=year200.getSelectedItem();
 tyear200=team.toString();
    }//GEN-LAST:event_year200ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new twoDatesIP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox day100;
    private javax.swing.JComboBox day200;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JComboBox month100;
    private javax.swing.JComboBox month200;
    private javax.swing.JComboBox year100;
    private javax.swing.JComboBox year200;
    // End of variables declaration//GEN-END:variables

}
